(tests
 (names
  doc_examples
  test_operations
  test_ite_constant
  test_shortest_sat
  test_isop
  test_logical_checks
  test_combine_same_theory
  test_restrict_paths
  repro_recursion
  test_properties
  test_model
  test_benchmark
  test_performance)
 (libraries theo theo_test_support qcheck unix))
